# Generated by Django 4.2.10 on 2026-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0002_alter_delegationforecast_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delegation_name", models.CharField(db_index=True, max_length=255)),
                ("governorate", models.CharField(blank=True, max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("linear_trend", "Linear Trend"),
                            ("nbeats", "N-BEATS"),
                            ("tft", "Temporal Fusion Transformer"),
                        ],
                        default="linear_trend",
                        max_length=50,
                    ),
                ),
                ("history_months", models.IntegerField()),
                ("median_mape", models.FloatField(blank=True, null=True)),
                ("p90_mape", models.FloatField(blank=True, null=True)),
                ("max_mape", models.FloatField(blank=True, null=True)),
                ("n_backtest_windows", models.IntegerField(default=0)),
                ("regime_shift_windows", models.JSONField(blank=True, default=list)),
                ("conformal_quantile", models.FloatField(blank=True, null=True)),
                ("conformal_coverage", models.FloatField(default=0.9)),
                ("conformal_n_calibration", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("champion", "In production"),
                            ("challenger", "Testing"),
                            ("retired", "Replaced"),
                        ],
                        default="champion",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("retrain_reason", models.TextField(blank=True)),
                ("qualified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Forecast Model Version",
                "verbose_name_plural": "Forecast Model Versions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delegation_name", "property_type", "is_active"],
                        name="forecast_fo_delegat_420b44_idx",
                    ),
                    models.Index(
                        fields=["model_type", "qualified"],
                        name="forecast_fo_model_t_379b42_idx",
                    ),
                ],
                "unique_together": {("delegation_name", "property_type", "status")},
            },
        ),
    ]
