# Generated by Django 5.2.17 on 2026-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0003_forecastmodelversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegationforecast",
            name="model_mape_pct",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
