# Generated by Django 4.2.10 on 2026-05-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delegationforecast",
            options={
                "ordering": ["delegation_name", "property_type", "horizon_idx"],
                "verbose_name": "Delegation Forecast",
                "verbose_name_plural": "Delegation Forecasts",
            },
        ),
        migrations.AlterModelOptions(
            name="delegationpricedata",
            options={
                "ordering": ["governorate", "delegation_name", "property_type"],
                "verbose_name": "Delegation Price Data",
                "verbose_name_plural": "Delegation Price Data",
            },
        ),
        migrations.RenameIndex(
            model_name="delegationforecast",
            new_name="forecast_de_delegat_6e5d7d_idx",
            old_name="forecast_df_del_orig_pt_idx",
        ),
        migrations.RenameIndex(
            model_name="delegationforecast",
            new_name="forecast_de_governo_43920e_idx",
            old_name="forecast_df_gov_h_pt_idx",
        ),
        migrations.RenameIndex(
            model_name="delegationforecast",
            new_name="forecast_de_propert_f1b3bc_idx",
            old_name="forecast_df_pt_h_idx",
        ),
        migrations.RenameIndex(
            model_name="delegationpricedata",
            new_name="forecast_de_governo_55fdf6_idx",
            old_name="forecast_dp_gov_pt_idx",
        ),
        migrations.RenameIndex(
            model_name="delegationpricedata",
            new_name="forecast_de_propert_358955_idx",
            old_name="forecast_dp_pt_avg_idx",
        ),
    ]
