# Generated by Django 4.2.10 on 2026-05-19 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentAccuracyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("total_queries_tested", models.IntegerField()),
                ("correct_predictions", models.IntegerField()),
                ("accuracy", models.FloatField()),
                ("accuracy_by_intent", models.JSONField(default=dict)),
                ("confusion_matrix", models.JSONField(default=dict)),
                ("test_set_size", models.IntegerField()),
            ],
            options={
                "db_table": "intent_accuracy_metric",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseQualityDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("total_responses", models.IntegerField()),
                ("good_responses", models.IntegerField()),
                ("acceptable_responses", models.IntegerField()),
                ("poor_responses", models.IntegerField()),
                ("avg_relevance_score", models.FloatField()),
                ("avg_groundedness_score", models.FloatField()),
                ("avg_overall_score", models.FloatField()),
                ("fully_grounded_count", models.IntegerField()),
                ("grounding_rate", models.FloatField()),
                ("total_feedback_received", models.IntegerField()),
                ("thumbs_up_count", models.IntegerField()),
                ("thumbs_down_count", models.IntegerField()),
                ("feedback_rate", models.FloatField()),
                ("top_intents", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "response_quality_daily_report",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="RewardModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("trained_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("training_examples", models.IntegerField()),
                ("thumbs_up_count", models.IntegerField()),
                ("thumbs_down_count", models.IntegerField()),
                ("cross_val_auc", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "artifact_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "reward_model_version",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("turn_count", models.IntegerField(default=0)),
                (
                    "primary_location_interest",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "investment_horizon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current", "Current"),
                            ("12_months", "12 Months"),
                            ("long_term", "Long Term"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "memory_snapshot",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_session",
            },
        ),
        migrations.CreateModel(
            name="ChatbotResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_index", models.IntegerField()),
                ("intent", models.CharField(db_index=True, max_length=50)),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("groundedness_score", models.FloatField(blank=True, null=True)),
                ("length_appropriate", models.BooleanField(blank=True, null=True)),
                ("has_source_attribution", models.BooleanField(blank=True, null=True)),
                (
                    "overall_quality_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "quality_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD", "Good"),
                            ("ACCEPTABLE", "Acceptable"),
                            ("POOR", "Poor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ungrounded_claims", models.JSONField(blank=True, default=list)),
                ("retrieval_sources_used", models.JSONField(blank=True, default=list)),
                ("is_grounded", models.BooleanField(blank=True, null=True)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("thumbs_down", "Thumbs Down"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="chatbot.chatbotsession",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_response_log",
            },
        ),
        migrations.AddIndex(
            model_name="chatbotsession",
            index=models.Index(
                fields=["session_id"], name="chatbot_ses_session_c803ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotsession",
            index=models.Index(
                fields=["started_at"], name="chatbot_ses_started_e81994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotsession",
            index=models.Index(
                fields=["last_active_at"], name="chatbot_ses_last_ac_f795b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotsession",
            index=models.Index(fields=["user"], name="chatbot_ses_user_id_aafef2_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotresponselog",
            index=models.Index(
                fields=["session", "turn_index"], name="chatbot_res_session_40d88f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotresponselog",
            index=models.Index(
                fields=["overall_quality_score"], name="chatbot_res_overall_bc7504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotresponselog",
            index=models.Index(
                fields=["user_feedback"], name="chatbot_res_user_fe_95bd43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotresponselog",
            index=models.Index(
                fields=["created_at"], name="chatbot_res_created_105993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotresponselog",
            index=models.Index(
                fields=["intent", "quality_label"], name="chatbot_res_intent_1e1acc_idx"
            ),
        ),
    ]
