# Generated by Django 4.2.10 on 2026-05-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_add_feedback_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatbotresponselog",
            name="feedback_date_idx",
        ),
    ]
