# Generated by Django 5.2.17 on 2026-10-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_remove_chatbotresponselog_feedback_date_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsession",
            name="preferred_property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
