# Generated by Django 4.2.10 on 2026-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delegation_price_benchmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="geocoding_precision",
            field=models.CharField(
                blank=True,
                choices=[("polygon", "Polygon Level"), ("centroid", "Centroid Level")],
                max_length=20,
                null=True,
            ),
        ),
    ]
