# Generated by Django 4.2.10 on 2026-05-14 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_property_geocoding_precision"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardKPIAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kpi_name", models.CharField(max_length=80)),
                ("flagged_value", models.FloatField()),
                ("z_score", models.FloatField(blank=True, null=True)),
                ("rolling_mean", models.FloatField(blank=True, null=True)),
                ("rolling_std", models.FloatField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=80)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Dashboard KPI Anomaly",
                "verbose_name_plural": "Dashboard KPI Anomalies",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardKPIMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpi_name",
                    models.CharField(
                        choices=[
                            ("national_median_price", "National Median Price"),
                            ("national_listing_volume", "National Listing Volume"),
                            ("top_growing_delegations", "Top Growing Delegations"),
                            ("top_yield_delegations", "Top Yield Delegations"),
                            ("climate_risk_summary", "Climate Risk Summary"),
                            ("forecast_national", "National Forecast"),
                        ],
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                ("source_app", models.CharField(max_length=40)),
                ("row_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard KPI Metadata",
                "verbose_name_plural": "Dashboard KPI Metadata",
                "ordering": ["kpi_name"],
            },
        ),
        migrations.CreateModel(
            name="MarketAnalyticsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("national_median_price_sqm", models.FloatField(default=0)),
                ("national_listing_count", models.IntegerField(default=0)),
                ("national_avg_days_on_market", models.FloatField(default=0)),
                ("top_growing_delegations", models.JSONField(blank=True, default=list)),
                ("top_yield_delegations", models.JSONField(blank=True, default=list)),
                ("delegation_distribution", models.JSONField(blank=True, default=dict)),
                ("property_type_breakdown", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("anomaly_checked", models.BooleanField(default=False)),
                ("anomaly_flagged", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Market Analytics Daily",
                "verbose_name_plural": "Market Analytics Daily",
                "ordering": ["-date"],
            },
        ),
    ]
