# Generated by Django 4.2.10 on 2026-05-19 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_dashboardkpianomaly_dashboardkpimetadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateRecalibrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("delegations_processed", models.IntegerField()),
                ("delegations_changed_significantly", models.IntegerField(default=0)),
                ("significant_changes", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("celery_beat", "Celery Beat"),
                            ("manual_admin", "Manual Admin"),
                            ("api_trigger", "API Trigger"),
                        ],
                        default="celery_beat",
                        max_length=50,
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failure", "Failure"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Climate Recalibration Event",
                "verbose_name_plural": "Climate Recalibration Events",
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="DelegationClimateScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "composite_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "composite_uncertainty",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "ci_lower_95",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="95% CI Lower",
                    ),
                ),
                (
                    "ci_upper_95",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="95% CI Upper",
                    ),
                ),
                (
                    "risk_label",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Very Low"),
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("MODERATE_HIGH", "Moderate-High"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                (
                    "flood_risk_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("flood_risk_uncertainty", models.FloatField(default=0.15)),
                (
                    "heat_stress_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("heat_stress_uncertainty", models.FloatField(default=0.1)),
                (
                    "coastal_erosion_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("coastal_erosion_uncertainty", models.FloatField(default=0.2)),
                (
                    "infrastructure_resilience_score",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "infrastructure_resilience_uncertainty",
                    models.FloatField(default=0.08),
                ),
                (
                    "wildfire_risk_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("wildfire_risk_uncertainty", models.FloatField(default=0.06)),
                ("computed_at", models.DateTimeField()),
                ("data_vintage", models.DateField(blank=True, null=True)),
                (
                    "computation_method",
                    models.CharField(default="composite_weighted", max_length=50),
                ),
                (
                    "delegation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_score",
                        to="core.delegation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegation Climate Score",
                "verbose_name_plural": "Delegation Climate Scores",
                "ordering": ["delegation__region__governorate", "delegation__name"],
            },
        ),
    ]
