# Generated by Django 5.2.17 on 2026-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_climaterecalibrationevent_delegationclimatescore"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegationmarketsnapshot",
            name="real_listing_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="delegationmarketsnapshot",
            name="synthetic_listing_count",
            field=models.IntegerField(default=0),
        ),
    ]
