# Generated by Django 5.2.17 on 2026-09-30 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_property_imputed_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegationclimatescore",
            name="water_stress_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="delegationclimatescore",
            name="water_stress_uncertainty",
            field=models.FloatField(default=0.08),
        ),
    ]
