# Generated by Django 4.2.10 on 2026-05-16 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddingCollectionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=100, unique=True)),
                ("domain", models.CharField(max_length=50)),
                ("embedding_model", models.CharField(max_length=200)),
                ("embedding_version", models.CharField(max_length=20)),
                ("total_passages", models.IntegerField(default=0)),
                ("indexed_date", models.DateField(default=django.utils.timezone.now)),
                ("recall_at_5", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="indexing", max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
