# Generated by Django 5.2.17 on 2026-09-27 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalResponseQualityDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("total_responses", models.IntegerField()),
                ("outcome_counts", models.JSONField(default=dict)),
                ("answered_count", models.IntegerField()),
                ("refusal_rate", models.FloatField()),
                ("good_responses", models.IntegerField()),
                ("acceptable_responses", models.IntegerField()),
                ("poor_responses", models.IntegerField()),
                ("avg_relevance_score", models.FloatField()),
                ("avg_groundedness_score", models.FloatField()),
                ("avg_overall_score", models.FloatField()),
                ("grounding_rate", models.FloatField()),
                ("total_feedback_received", models.IntegerField()),
                ("thumbs_up_count", models.IntegerField()),
                ("thumbs_down_count", models.IntegerField()),
                ("feedback_rate", models.FloatField()),
                ("top_domains", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "legal_response_quality_daily_report",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="LegalRewardModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("trained_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("training_examples", models.IntegerField()),
                ("thumbs_up_count", models.IntegerField()),
                ("thumbs_down_count", models.IntegerField()),
                ("cross_val_auc", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "artifact_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "legal_reward_model_version",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("turn_count", models.IntegerField(default=0)),
                (
                    "last_domain",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "memory_snapshot",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "legal_session",
            },
        ),
        migrations.CreateModel(
            name="LegalResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_index", models.IntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, default="", max_length=5)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "Answered, grounded"),
                            (
                                "answered_flagged",
                                "Answered, some sentences not verified",
                            ),
                            ("refused_no_sources", "Refused: no relevant legal source"),
                            (
                                "refused_ungrounded",
                                "Refused: answer not supported by sources",
                            ),
                            ("out_of_scope", "Not a legal question"),
                            ("llm_unavailable", "Language model unreachable"),
                            ("error", "Internal error"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                ("domain_confidence", models.FloatField(blank=True, null=True)),
                ("in_scope", models.BooleanField(blank=True, null=True)),
                (
                    "collection_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("retrieval_top_similarity", models.FloatField(blank=True, null=True)),
                ("retrieval_sources", models.JSONField(blank=True, default=list)),
                ("llm_model", models.CharField(blank=True, default="", max_length=100)),
                ("generation_attempts", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("groundedness_score", models.FloatField(blank=True, null=True)),
                ("citation_score", models.FloatField(blank=True, null=True)),
                ("length_appropriate", models.BooleanField(blank=True, null=True)),
                (
                    "overall_quality_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "quality_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD", "Good"),
                            ("ACCEPTABLE", "Acceptable"),
                            ("POOR", "Poor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_grounded", models.BooleanField(blank=True, null=True)),
                ("ungrounded_sentences", models.JSONField(blank=True, default=list)),
                ("reward_score", models.FloatField(blank=True, null=True)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("thumbs_down", "Thumbs Down"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("feedback_text", models.TextField(blank=True, null=True)),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="legal.legalsession",
                    ),
                ),
            ],
            options={
                "db_table": "legal_response_log",
            },
        ),
        migrations.AddIndex(
            model_name="legalsession",
            index=models.Index(
                fields=["last_active_at"], name="legal_sessi_last_ac_5a6469_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalsession",
            index=models.Index(fields=["user"], name="legal_sessi_user_id_0c3ab2_idx"),
        ),
        migrations.AddIndex(
            model_name="legalresponselog",
            index=models.Index(
                fields=["session", "turn_index"], name="legal_respo_session_0abf40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalresponselog",
            index=models.Index(
                fields=["created_at"], name="legal_respo_created_0c8482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalresponselog",
            index=models.Index(
                fields=["outcome", "quality_label"],
                name="legal_respo_outcome_a3c81d_idx",
            ),
        ),
    ]
