# Generated by Django 5.2.17 on 2026-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_session_response_log_quality_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalresponselog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("answered", "Answered, grounded"),
                    ("answered_flagged", "Answered, some sentences not verified"),
                    (
                        "answered_extractive",
                        "Answered with quotations from the sources (no language model)",
                    ),
                    ("refused_no_sources", "Refused: no relevant legal source"),
                    ("refused_ungrounded", "Refused: answer not supported by sources"),
                    ("out_of_scope", "Not a legal question"),
                    ("llm_unavailable", "Language model unreachable"),
                    ("error", "Internal error"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
