# Generated by Django 4.2.10 on 2026-05-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_module10_hardening"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentcalibrationprofile",
            new_name="simulation__agent_t_3503f0_idx",
            old_name="calib_agent_active_idx",
        ),
        migrations.RenameIndex(
            model_name="agentcalibrationprofile",
            new_name="simulation__calibra_443774_idx",
            old_name="calib_date_active_idx",
        ),
        migrations.RenameIndex(
            model_name="simulationrun",
            new_name="simulation__user_id_c9419e_idx",
            old_name="simulation_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="simulationrun",
            new_name="simulation__scenari_2f58be_idx",
            old_name="simulation_scenario_completed_idx",
        ),
    ]
