# Generated by Django 5.2.17 on 2026-09-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulation",
            "0004_rename_calib_agent_active_idx_simulation__agent_t_3503f0_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulation_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
