# Generated by Django 4.2.10 on 2026-05-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Portfolio Asset",
                "verbose_name_plural": "Portfolio Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="scanresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Scan Result",
                "verbose_name_plural": "Scan Results",
            },
        ),
    ]
