# Generated by Django 4.2.10 on 2026-05-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("valuation", "0007_delegationforecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuationModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=20)),
                ("artifact_path", models.CharField(max_length=255)),
                ("training_date", models.DateField()),
                ("training_data_hash", models.CharField(max_length=64)),
                ("training_samples", models.IntegerField(default=0)),
                ("eval_rmse", models.FloatField(default=0)),
                ("eval_r2", models.FloatField(default=0)),
                ("eval_mape", models.FloatField(default=0)),
                ("eval_holdout_size", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("challenger", "Challenger — A/B testing"),
                            ("champion", "Champion — 100% traffic"),
                            ("retired", "Retired — replaced"),
                            ("failed", "Failed — rejected"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("ab_traffic_pct", models.IntegerField(default=0)),
                ("promoted_by", models.CharField(blank=True, max_length=80)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("calibration_profile", models.JSONField(blank=True, default=dict)),
                ("drift_profile", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("model_name", "version")},
            },
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="model_artifact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="model_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="model_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="ValuationPredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("model_version_label", models.CharField(blank=True, max_length=20)),
                ("input_hash", models.CharField(max_length=64)),
                ("input_features", models.JSONField(default=dict)),
                ("prediction_tnd", models.FloatField()),
                ("confidence_low", models.FloatField()),
                ("confidence_high", models.FloatField()),
                ("confidence_level", models.CharField(max_length=10)),
                ("fallback_used", models.BooleanField(default=False)),
                ("latency_ms", models.IntegerField(default=0)),
                ("snapshot_date", models.DateField(blank=True, null=True)),
                ("actual_tnd", models.FloatField(blank=True, null=True)),
                ("actual_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calibration_state",
                    models.CharField(default="pending", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="valuation.valuationmodelversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_version", "created_at"],
                        name="valuation_v_model_v_c4ea49_idx",
                    ),
                    models.Index(
                        fields=["model_name", "created_at"],
                        name="valuation_v_model_n_85c374_idx",
                    ),
                ],
            },
        ),
    ]
