# Generated by Django 5.2.17 on 2026-09-27 09:17
"""Drop valuation.DelegationForecast; forecast.DelegationForecast is canonical.

The dropped table held the h12_v1 output of the original ML forecasting
project, whose source files no longer exist. Before the table is dropped,
every row is written to a CSV so no environment loses that data:

    <DATA_DIR>/archive/valuation_delegationforecast_<db alias>_<UTC timestamp>.csv

A copy taken from the development database is also committed at
forecast/data/archive/delegation_forecast_h12_v1.csv.
"""
import csv
from datetime import datetime, timezone

from django.db import migrations


def archive_rows(apps, schema_editor):
    from config.paths import DATA_DIR

    DelegationForecast = apps.get_model("valuation", "DelegationForecast")
    alias = schema_editor.connection.alias
    qs = DelegationForecast.objects.using(alias).order_by("delegation_name", "forecast_origin", "horizon_idx")
    if not qs.exists():
        return

    fields = [
        "delegation_name", "governorate", "delegation_fk_id", "forecast_origin",
        "forecast_month", "horizon_idx", "predicted_price_per_m2",
        "model_mape_pct", "model_version", "created_at",
    ]
    archive_dir = DATA_DIR / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = archive_dir / f"valuation_delegationforecast_{alias}_{stamp}.csv"
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(fields)
        for row in qs.values_list(*fields).iterator():
            writer.writerow(row)
    print(f"\n  Archived {qs.count()} valuation.DelegationForecast rows to {path}")


class Migration(migrations.Migration):

    dependencies = [
        ("valuation", "0008_valuationmodelversion_and_more"),
    ]

    operations = [
        migrations.RunPython(archive_rows, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="DelegationForecast",
        ),
    ]
