# Generated by Django 5.2.17 on 2026-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation", "0011_registry_keys_per_serving_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valuationmodelversion",
            name="version",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="valuationpredictionlog",
            name="model_version_label",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="valuationrequest",
            name="model_version",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
