# Generated by Django 4.2.10 on 2026-05-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investor", "0002_alter_portfolioasset_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationAuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_date", models.DateField()),
                ("lookback_months", models.IntegerField(default=6)),
                ("grade_a_count", models.IntegerField(default=0)),
                ("grade_a_mean_return", models.FloatField(default=0.0)),
                ("grade_a_std_return", models.FloatField(default=0.0)),
                ("grade_b_count", models.IntegerField(default=0)),
                ("grade_b_mean_return", models.FloatField(default=0.0)),
                ("grade_b_std_return", models.FloatField(default=0.0)),
                ("grade_c_count", models.IntegerField(default=0)),
                ("grade_c_mean_return", models.FloatField(default=0.0)),
                ("grade_c_std_return", models.FloatField(default=0.0)),
                ("grade_d_count", models.IntegerField(default=0)),
                ("grade_d_mean_return", models.FloatField(default=0.0)),
                ("grade_d_std_return", models.FloatField(default=0.0)),
                ("is_monotonic", models.BooleanField(default=False)),
                (
                    "calibration_status",
                    models.CharField(
                        choices=[
                            ("PASS", "Calibration OK"),
                            ("WARN", "Calibration Warning"),
                            ("FAIL", "Calibration Failed"),
                        ],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                ("inversions_detected", models.JSONField(default=list)),
                ("recommended_action", models.TextField(blank=True)),
                ("weights_before", models.JSONField(default=dict)),
                ("weights_suggested", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Calibration Audit Record",
                "verbose_name_plural": "Calibration Audit Records",
                "ordering": ["-audit_date"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("total_value_tnd", models.FloatField()),
                ("asset_count", models.IntegerField()),
                ("delegation_count", models.IntegerField()),
                ("blended_gross_yield_pct", models.FloatField()),
                ("blended_net_yield_pct", models.FloatField()),
                ("blended_irr_pct", models.FloatField()),
                ("irr_pessimistic_pct", models.FloatField()),
                ("irr_optimistic_pct", models.FloatField()),
                ("portfolio_volatility_pct", models.FloatField()),
                ("diversification_ratio", models.FloatField()),
                ("concentration_pct", models.FloatField()),
                ("climate_risk_score", models.FloatField()),
                ("climate_risk_label", models.CharField(max_length=20)),
                ("concentration_alerts", models.JSONField(default=list)),
                ("correlation_alerts", models.JSONField(default=list)),
                ("diversification_suggestions", models.JSONField(default=list)),
                ("climate_alerts", models.JSONField(default=list)),
                ("covariance_matrix", models.JSONField(default=dict)),
                ("correlation_matrix", models.JSONField(default=dict)),
                ("full_analysis", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Analysis",
                "verbose_name_plural": "Portfolio Analyses",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="InvestorScorerVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scorer_name",
                    models.CharField(
                        choices=[
                            ("undervaluation_detector", "Undervaluation Detector"),
                            ("yield_estimator", "Yield Estimator"),
                            ("buy_wait_classifier", "Buy/Wait Classifier"),
                            ("opportunity_scorer", "Opportunity Scorer"),
                            ("investment_grader", "Investment Grader"),
                            ("irr_calculator", "IRR Calculator"),
                            ("portfolio_risk_assessor", "Portfolio Risk Assessor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("champion", "Champion (Active)"),
                            ("challenger", "Challenger (Testing)"),
                            ("retired", "Retired"),
                        ],
                        default="challenger",
                        max_length=20,
                    ),
                ),
                ("training_date", models.DateTimeField()),
                ("training_sample_count", models.IntegerField()),
                ("validation_metric_primary", models.FloatField()),
                ("validation_metric_primary_name", models.CharField(max_length=100)),
                (
                    "validation_metric_secondary",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "validation_metric_secondary_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("promoted_by", models.CharField(blank=True, max_length=100)),
                (
                    "rollback_to_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ab_test_active", models.BooleanField(default=False)),
                ("ab_test_traffic_pct", models.FloatField(default=0.0)),
                ("ab_test_start_date", models.DateField(blank=True, null=True)),
                ("ab_test_end_date", models.DateField(blank=True, null=True)),
                (
                    "ab_test_result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WINNER", "Won A/B Test"),
                            ("LOSER", "Lost A/B Test"),
                            ("INCONCLUSIVE", "Inconclusive"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("artifact_path", models.CharField(max_length=255)),
                ("artifact_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Investor Scorer Version",
                "verbose_name_plural": "Investor Scorer Versions",
                "ordering": ["-created_at"],
                "unique_together": {("scorer_name", "version")},
            },
        ),
        migrations.CreateModel(
            name="InvestmentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_date", models.DateTimeField(auto_now_add=True)),
                ("property_price_tnd", models.FloatField()),
                ("delegation", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=20)),
                ("room_count", models.IntegerField()),
                ("surface_m2", models.FloatField()),
                ("undervaluation_score", models.FloatField()),
                ("undervaluation_label", models.CharField(blank=True, max_length=30)),
                ("gross_yield_pct", models.FloatField()),
                ("net_yield_pct", models.FloatField()),
                ("yield_confidence", models.CharField(max_length=20)),
                ("buy_signal", models.CharField(max_length=20)),
                ("buy_signal_confidence", models.FloatField()),
                ("opportunity_score", models.FloatField()),
                ("score_breakdown", models.JSONField(default=dict)),
                (
                    "investment_grade",
                    models.CharField(
                        choices=[
                            ("A", "Strong Buy"),
                            ("B", "Buy"),
                            ("C", "Hold"),
                            ("D", "Wait"),
                            ("F", "Avoid"),
                        ],
                        max_length=5,
                    ),
                ),
                ("irr_base_pct", models.FloatField()),
                ("irr_pessimistic_pct", models.FloatField()),
                ("irr_optimistic_pct", models.FloatField()),
                ("irr_holding_years", models.IntegerField(default=10)),
                ("risk_score", models.FloatField()),
                ("risk_label", models.CharField(max_length=20)),
                ("key_drivers", models.JSONField(default=list)),
                ("alerts", models.JSONField(default=list)),
                ("shap_explanations", models.JSONField(default=dict)),
                ("models_version", models.JSONField(default=dict)),
                ("full_analysis", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investment_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Score",
                "verbose_name_plural": "Investment Scores",
                "ordering": ["-score_date"],
            },
        ),
        migrations.CreateModel(
            name="BuyWaitPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                ("property_price_tnd", models.FloatField()),
                ("delegation", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=20)),
                ("room_count", models.IntegerField()),
                ("surface_m2", models.FloatField()),
                ("delegation_momentum_3m", models.FloatField()),
                ("delegation_momentum_12m", models.FloatField()),
                ("opportunity_score", models.FloatField()),
                ("undervaluation_pct", models.FloatField()),
                ("estimated_net_yield", models.FloatField()),
                ("portfolio_concentration_pct", models.FloatField()),
                ("climate_risk_score", models.FloatField()),
                ("national_interest_rate", models.FloatField()),
                ("delegation_dom", models.FloatField()),
                ("p_good_buy", models.FloatField()),
                ("predicted_signal", models.CharField(max_length=20)),
                ("shap_drivers", models.JSONField(default=dict)),
                ("model_version", models.CharField(max_length=20)),
                ("ab_cohort", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buy_wait_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buy/Wait Prediction",
                "verbose_name_plural": "Buy/Wait Predictions",
                "ordering": ["-prediction_date"],
            },
        ),
    ]
