# Generated by Django 5.2.17 on 2026-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investor", "0003_calibrationauditrecord_portfolioanalysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationauditrecord",
            name="calibration_status",
            field=models.CharField(
                choices=[
                    ("PASS", "Calibration OK"),
                    ("WARN", "Calibration Warning"),
                    ("FAIL", "Calibration Failed"),
                    (
                        "INSUFFICIENT_DATA",
                        "Not enough scored properties with a measurable return",
                    ),
                ],
                default="PASS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="calibrationauditrecord",
            name="is_monotonic",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
