# Generated by Django 4.2.10 on 2026-05-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_useractivity_activity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Portfolio Asset",
                "verbose_name_plural": "Portfolio Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="savedproperty",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Saved Property",
                "verbose_name_plural": "Saved Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
    ]
