# Generated by Django 4.2.10 on 2026-05-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationrun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Simulation Run",
                "verbose_name_plural": "Simulation Runs",
            },
        ),
    ]
